dependencies:
- name: postgresql
  version: 10.5.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: redis
  version: 4.0.11
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: sidekiq
  
